#!/usr/bin/env python
"""Stage 2, part 1: generate readable concept labels.

OULAD provides no titles for learning materials, so a concept's subject matter is
genuinely unknown. Rather than invent topic names, labels describe what the data does
support: position in the module, activity composition, and whether an assessment falls
there. Every label is derived; none is asserted.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from elpr.db.duckdb_runner import SQLRunner  # noqa: E402

GRAPH_DIR = ROOT / "graph"

PHASE = [(0.15, "opening"), (0.40, "early"), (0.65, "middle"), (0.85, "late"), (1.01, "final")]
ACTIVITY_PHRASE = {
    "content": "reading and course content",
    "quiz": "quizzes and self-assessment",
    "discussion": "forum and collaboration",
    "reference": "reference material",
}


def phase_of(progress: float) -> str:
    for threshold, name in PHASE:
        if progress <= threshold:
            return name
    return "final"


def build_label(row) -> str:
    from elpr.modules import display_name
    parts = [f"{display_name(row.code_module)} · Week {row.week:02d}"]
    descriptors = [phase_of(row.progress or 0.0)]
    if row.has_assessment:
        descriptors.append(
            "assessment week" if row.n_assessments == 1 else f"{row.n_assessments} assessments"
        )
    phrase = ACTIVITY_PHRASE.get(row.dominant_activity, row.dominant_activity)
    # Only call the mix "mostly" X when it genuinely dominates.
    descriptors.append(f"mostly {phrase}" if (row.dominant_share or 0) >= 0.6 else phrase)
    return f"{parts[0]} ({', '.join(descriptors)})"


def main() -> int:
    runner = SQLRunner()
    print("Running SQL (sql/12):")
    runner.run_range(12, 12)

    rows = runner.df("SELECT * FROM concept_descriptors ORDER BY concept_id")
    labels = {}
    for row in rows.itertuples(index=False):
        labels[int(row.concept_id)] = {
            "key": row.concept_key,
            "label": build_label(row),
            "module": row.code_module,
            "week": int(row.week),
            "n_sites": int(row.n_sites),
            "n_students": int(row.n_students),
            "has_assessment": bool(row.has_assessment),
            "dominant_activity": row.dominant_activity,
        }

    GRAPH_DIR.mkdir(parents=True, exist_ok=True)
    out = GRAPH_DIR / "concept_labels.yaml"
    out.write_text(
        "# Generated by scripts/07_concept_labels.py, derived from OULAD activity\n"
        "# composition and assessment placement. OULAD ships no material titles, so no\n"
        "# subject matter is asserted. Edit by hand only with a documented source.\n"
        + yaml.safe_dump(labels, sort_keys=True, allow_unicode=True, width=100)
    )

    print(f"\nWrote {out.relative_to(ROOT)} ({len(labels)} concepts)")
    print("\nSample:")
    for cid in list(labels)[:4] + list(labels)[120:123]:
        print(f"  {cid:>3}  {labels[cid]['label']}")

    print("\nActivity composition across concepts:")
    print(runner.df(
        "SELECT dominant_activity, COUNT(*) AS n_concepts, "
        "SUM(has_assessment::INT) AS with_assessment "
        "FROM concept_descriptors GROUP BY 1 ORDER BY n_concepts DESC"
    ).to_string(index=False))

    runner.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
